feat: allow sending a custom proxy timeout error
nodejitsu/node-http-proxy pull request #1650
Opened 2023-10-07 12:29 UTC by rowanmanning

When using `proxyTimeout` it's very difficult to tell the difference between a regular socket hangup and a timeout because, in both cases, an `ECONNRESET` error is thrown. Ideally we should be able to identify when a proxy request has failed because it took too long, this would allow us to do things like send appropriate `504` status code.

Suddenly throwing a different error would probably be considered a breaking change because it's possible that users of http-proxy are relying on the `ECONNRESET` error. I decided to add the custom timeout error behind a new option for now so that people can opt into using it.

If you set this option:

```js
var proxy = httpProxy.createProxyServer({
  target: 'http://example.com',
  proxyTimeout: 100,
  proxyTimeoutCustomError: true
});
```

Then the error that gets thrown will have a message of `"The proxy request timed out"` and a code of `ETIMEDOUT` to match Node.js: https://nodejs.org/api/errors.html#common-system-errors

This allows for custom error handling code like this:

```js
proxy.on('error', function(err, req, res) {
  if (err.code === 'ETIMEDOUT') {
    res.writeHead(504);
  } else {
    res.writeHead(503);
  }
  // ...
});
```

## A note on implementation

I had to switch from [`request.abort()`](https://nodejs.org/api/http.html#requestabort) to [`request.destroy()`](https://nodejs.org/api/http.html#requestdestroyerror) for this to work. `request.abort()` has been deprecated since Node.js v14.1.0 and `request.destroy()` has been available since Node.js v0.3.0 so I think this is a safe bet. If you're worried about it then I could always switch to `request.abort()` for the case when `proxyTimeoutCustomError` is falsy.

---

Resolves #1331.

2023-10-14 18:49 UTC, JoaoOtavioS commented
Hi, I took the liberty of implementing this in my fork. https://github.com/squarecloudofc/http-proxy

2024-10-29 21:07 UTC, ravin00 requested changes

2024-10-29 21:07 UTC, ravin00 commented on lib/http-proxy/passes/web-incoming.js
> +        proxyReq.destroy();
what the change here?

2024-10-29 21:07 UTC, ravin00 commented on test/lib-http-proxy-passes-web-incoming-test.js
> +        expect(new Date().getTime() - started).to.be.greaterThan(99);
what about adding the `expect(new Date().getTime() - started).to.be.above(99);
`. Will it make a difference to this line or to the whole code

2025-10-12 08:07 UTC, closed without merging